### ISSUE TITLE
Why not use ball queries in the sampling phase like PointNet++?

### ISSUE THREAD

**Issue by JongRok-Lee** [ShenZheng2000/PointNorm-for-Point-Cloud-Analysis#6]
hello!
Thank you for your research.

I have one question for you.
As per the title, is there any reason why you used KNN instead of using ball queries?

**Comment by ShenZheng2000** [comment]
Hey, Lee! Thank you for your question. We have chosen KNN over ball queries for the following reasons:

* KNN is computationally more efficient.

* KNN is more robust for sparse regions of the point cloud.

* Recent state-of-the-art methods, such as PointMLP, also utilize KNN instead of ball queries.
